# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MunchCoin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MunchCoin
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Kingfisher'
  target 'MunchCoinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MunchCoinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
